
category_list = ['Resistor',
                'Capacitor - MLCC',
                'Capacitor - Electrolytic',
                'Capacitor - Tantalum',
                'Inductor',
                'LED',
                'Diode',
                'Wireless Module',
                'Switch',
                'Transistor - MOSFET',
                'Transistor - BJT',
                'Crystal',
                'Antenna',
                'Fuse',
                'RF Filter',
                'Buzzer',
                'Sensor',
                'IC',
                'IC - Microcontroller',
                'IC - Flash Memory',
                'IC - LED Driver',
                'IC - Battery',
                'IC - Voltage Regulato',
                'Connector',
                'Connector - USB',
                'Connector - RF',
                'Connector - Audio',
                'Relay',
                'Resistor - Variable']

footprint_list = ['0402 (1005)',
                '0603 (1608)',
                '0805 (2012)',
                '1206 (3216)',
                '1210 (3225)',
                '1411 (3528)',
                '1414 (3535)',
                '2312 (6032)',
                '2917 (7343)',
                'SOD-23',
                'SMA',
                'SOD-80',
                'SOD-123',
                'SOD-323',
                'SOD-523',
                'SOD-128',
                'SOIC-8-EP',
                'SOIC-8',
                'SOIC-8-5.3W',
                'SOIC-16',
                'SOT-753',
                'SOT-23',
                'SOT-23-5',
                'SOT-23-6',
                'SOT-223',
                'SOT-223-6',
                'SOT-363-6',
                'SOT-89-3',
                'SOT-89-5',
                'QFN-28-5x5-EP',
                'QFN-48-6x6-0.4P-EP',
                'QFN-32-5x5-0.5P-EP',
                'QFN-20-3x3-EP',
                'TDFN-6-1x1',
                'QFN-16-4x4',
                'SOT-353',
                '4-X2SON (1x1)',
                'QFN-68-8x8',
                'WQFN-12-2x3',
                'QFN-32-5x5-EP',
                'aQFN-73-7x7-EP',
                'TQFN-32-7x7',
                'TO-263-6',
                'VSOP-8-0.5',
                'TSSOP-8',
                'TSSOP-14',
                'VFDFN-10',
                'LGA-14',
                'EC-4.3',
                'EC-5.3',
                'EC-6.6',
                'SMD5730',
                'SMD3535',
                'SMD5050',
                'SMD3215-2P',
                'SMD2520-4P',
                'SMD3225-4P',
                'TO-263-5',
                'DO-41',
                'DO-15',
                'DO-201AD',
                'DO-35',
                'DO-27',
                'TO-92',
                'TO-220',
                'DIP-18',
                'DIP-16',
                'DIP-8']